Practical task 3
S1NLESS1/dZibert pull request #3
Opened 2024-07-07 12:55 UTC by S1NLESS1

2024-07-07 21:04 UTC, ashiryaev requested changes

2024-07-07 21:04 UTC, ashiryaev commented on src/test/java/ru/dZibert/tgBot/FillingTests.java
> +        Category pizza_category = createCategory((long)1,"Пицца",null);
Можно использовать 1L вместо (long) 1 . Но в любом случае id устанавливать не нужно. У нас аннотация @GeneratedValue сгенерит автоматически id для сущности

2024-07-07 21:04 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/entity/Category.java
> +    private Long id; // уникальный идентификатор
Не знаю что за стиль кода. Но properties обычно раньше методом )) . Поправь во всех файлах, пож-ста.

2024-07-07 21:04 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/entity/Product.java
> +    private Category category; // категория товара
Короче, непонятно. Id выше, потом методы, потом опять properties. Приведи в порядок форматирование.

2024-07-08 10:18 UTC, ashiryaev requested changes

2024-07-08 10:18 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/entity/ClientOrder.java
> +    private Double total; // сумма по заказу
Для цен используем BigDecimal

2024-07-08 10:18 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/entity/Product.java
> +    public Double price; // стоимость
Для цен используем BigDecimal

2024-07-08 10:37 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/entity/ClientOrder.java
> +    private Double total; // сумма по заказу
Странно, в ценах точность вроде бы не так важна) 
В методических указаниях стоит double, я и использую Double

2024-07-08 11:44 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/entity/ClientOrder.java
> +    private Double total; // сумма по заказу
Там проблемы с округлением получаются. Это тип с плавающей запятой. У некоторых выдавало ошибку при использовании precision и тип Double. Попробуй оставить Double. Но мне кажется это немного неверно.

2024-07-08 11:54 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/entity/ClientOrder.java
> +    private Double total; // сумма по заказу
Скоро исправлю

2024-07-08 12:38 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/entity/Product.java
> +    public Double price; // стоимость
Исправил

2024-07-08 12:38 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/entity/ClientOrder.java
> +    private Double total; // сумма по заказу
Исправил

2024-07-08 13:34 UTC, ashiryaev approved these changes

2024-07-08 14:16 UTC, merged