Практическое задание №4. Реализовал REST API и сервисный слой
S1NLESS1/dZibert pull request #5
Opened 2024-07-09 18:10 UTC by S1NLESS1

2024-07-10 09:07 UTC, ashiryaev requested changes

2024-07-10 09:07 UTC, ashiryaev commented on REST PZ4/Get categories.bru
Без понятия, что это за файлы bru. Объяснишь зачем они нужны? )

2024-07-10 09:07 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/Service/AppService.java
Надо разделить на несколько сервисов по смыслу. Просто представь, что приложение будет расти.

2024-07-10 09:07 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/rest/AppRectController.java
Также надо разделить на несколько контроллеров по смыслу и отношению к сущностям.

2024-07-10 09:21 UTC, S1NLESS1 commented on REST PZ4/Get categories.bru
Это файлы коллекции из bruno. Я решил их с проектом вместе хранить)

2024-07-10 09:21 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/AppRectController.java
Это разве не доп.задание?

2024-07-10 09:22 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/Service/AppService.java
Это разве не доп задание?

2024-07-10 15:08 UTC, ashiryaev requested changes

2024-07-10 15:08 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/rest/CategoryRestController.java
> +    List<Category> getCategories(){
В задании не было задачи на создание этого метода вроде. Можно убрать и контроллер

2024-07-10 15:08 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/rest/OrderProductRestController.java
> +        return orderProductService.getClientProducts(id);
Это нужно добавить в ClientRestController

2024-07-10 15:08 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/rest/OrderProductRestController.java
> +        return orderProductService.getTopPopularProducts(limit);
Это добавить в ProductRestController.
OrderProductRestController можно удалить. 
Можно оставить только 2 контроллера Client и Product. По сервисам тоже самое. Можно 2-мя ограничиться.

2024-07-10 15:08 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/rest/ProductRestController.java
> +        return productService.getProducts();
Не нужен по заданию.

2024-07-10 15:08 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/Service/ClientOrderService.java
> +        ClientOrder exampleClientOrder = new ClientOrder();
Сложно разобраться, что здесь такое. Нужно как-то попроще сделать выборку по условию.

2024-07-10 15:10 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/CategoryRestController.java
> +    List<Category> getCategories(){
Для себя создавал для удобного просмотра в bruno

2024-07-10 15:11 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/OrderProductRestController.java
> +        return orderProductService.getTopPopularProducts(limit);
Так изначально и сделал. Просто ставилась задача "разделить REST-контроллеры на отдельные классы, чтобы каждый работал с одним ресурсом". Поэтому и разделял их по основному ресурсу, чтобы у каждого контроллера был один "репозиторий" открыт

2024-07-10 15:33 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/OrderProductRestController.java
> +        return orderProductService.getClientProducts(id);
Исправил

2024-07-10 15:33 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/OrderProductRestController.java
> +        return orderProductService.getTopPopularProducts(limit);
Исправил

2024-07-10 15:33 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/rest/ProductRestController.java
> +        return productService.getProducts();
Исправил

2024-07-10 15:33 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/Service/ClientOrderService.java
> +        ClientOrder exampleClientOrder = new ClientOrder();
Исправил

2024-07-10 15:56 UTC, ashiryaev requested changes

2024-07-10 15:56 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/Service/ProductService.java
> +        return productRepository.searchProductsByName('%'+name+'%');
Надо только name передавать. % - это специфика репозиториев

2024-07-10 15:56 UTC, ashiryaev commented on src/main/java/ru/dZibert/tgBot/Service/ClientService.java
> +        return clientRepository.searchClientsByName('%'+name+'%');
Надо только name передавать. % - это специфика репозиториев

2024-07-10 15:58 UTC, S1NLESS1 commented on src/main/java/ru/dZibert/tgBot/Service/ProductService.java
> +        return productRepository.searchProductsByName('%'+name+'%');
В таком случае всё моё решение рассыпается(

2024-07-11 07:12 UTC, ashiryaev approved these changes

2024-07-11 07:58 UTC, merged